tap "homebrew/bundle"
tap "homebrew/cask"
tap "homebrew/cask-versions"
tap "homebrew/core"
tap "adoptopenjdk/openjdk"

brew "mas"
brew "node"
brew "pandoc"
brew "rclone"
brew "python"

cask "1password"
cask "adoptopenjdk"
cask "alfred"
cask "anki"
cask "bartender"
cask "calibre"
cask "discord"
cask "firefox"
cask "google-chrome"
cask "google-drive-file-stream"
cask "intellij-idea"
cask "datagrip"
cask "istat-menus"
cask "iterm2"
cask "mactex-no-gui"
cask "menumeters"
cask "microsoft-office"
cask "microsoft-teams"
cask "minecraft"
cask "numi"
cask "slack"
cask "spotify"
cask "tiles"
cask "visual-studio-code"
cask "webex-meetings"
cask "zoomus"

mas "1Blocker", id: 1107421413
mas "Accelerate", id: 1459809092
mas "Bear", id: 1091189122
mas "Flow", id: 1423210932
mas "GoodNotes", id: 1444383602
mas "Instapaper Save", id: 1481302432
mas "Keynote", id: 409183694
mas "Numbers", id: 409203825
mas "Pages", id: 409201541
mas "Trello", id: 1278508951
mas "Ulysses", id: 1225570693
mas "Xcode", id: 497799835
mas "Reeder", id: 1449412482