# Custom prompt
# username@hostname pwd $
yellow=$(tput setaf 3)
normal=$(tput sgr0)
blue=$(tput setaf 4)
green=$(tput setaf 2)
# PS1="\[$yellow\]\u\[$normal\]@\[$blue\]\h \[$green\]\W \[$normal\]$ "
# PS1="[\u@\h:\W] $ "
PS1="[\[$green\]\u\[$green\]@\[$green\]\h\[$normal\]:\[$blue\]\W\[$normal\]] $ "

# Aliases
alias ls="ls --color=auto -Fh"
alias ll="ls -l"
alias la="ll -A"
alias grep="grep --color=auto"

# Set editor to neovim
export EDITOR=nvim

# Set emacs-style keybindings
# This is the default, but zsh automatically sets vim-style keybindings when EDITOR is vim
set -o emacs
